### ISSUE TITLE
make create functions more generic wrappers

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseformation#8]
Couldn't kwargs just be passed to the object constructors? This would enable the args to come more directly from the JSON that we'll eventually consume to run these functions.

**Comment by thomasyu888** [comment]
I see, so what you're thinking is

```
def _create(constructor, **kwargs):
    constructor_ent = constructor(**kwargs)
    return syn.store(constructor_ent)
```

**Comment by kdaily** [comment]
Here's how I did this in the Gates project:

A generic function to find it or create:

https://github.com/Sage-Bionetworks/ki-rally-manager/blob/master/kirallymanager/manager.py#L161-L178

Example creating an entity view:

https://github.com/Sage-Bionetworks/ki-rally-manager/blob/master/kirallymanager/manager.py#L133-L146

**Comment by kdaily** [comment]
It is harder than this because not everything is an entity - Teams and Wikis will work differently. I think it's abstractable though.
