### ISSUE TITLE
`create_or_update` param name is confusing

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseformation#9]
Not quite clear by the name, because nothing is 'updated' in the current code - it only returns existing objects if they exist. Maybe it's because the param is performing two duties - one to decide to try and get an existing object, and another to pass to the `store` function to do the create or update?

**Comment by thomasyu888** [comment]
The `create_or_update` is just pulled from the `syn.store` function.  I can definitely rename it.

**Comment by kdaily** [comment]
It seems to mean something different when used here (with the `if self.create_or_update` check).

**Comment by thomasyu888** [comment]
ya, you're absolutely right.  I think I need to go the route that you did in `create_or_find` and not necessarily `create_or_update`.  I will use the function that you wrote in `kirally` as noted #8 

My purpose of using this flag was really to `create_or_find` but I realize now that `syn.store` will update the entities one has access to by default, not just retrieve the existing entity.
